permission: "lunatic.coord"
task_timer: 10 #minutos
mysql:
  host: 178.255.219.105
  user: u2170_CnMdkhQlXG
  password: 9m!OzZvRmd+RuFeVJuj+Nh5r
  database: s2170_lunatic
  port: 3306
magnata: "&2[$]"
top:
  title: "&8Top Money"
  hotbars: 4
  decoration:
    item: 160;15
    name: "&7"
  item:
    name: "&6{position}. &f{player}"
    lore:
      - ""
      - "&7Dinheiro em conta: &f{amount}"
      - ""
  slots:
    1: 10
    2: 11
    3: 12
    4: 13
    5: 14
    6: 15
    7: 16
    8: 21
    9: 22
    10: 23